 -  test_name: InfrastructureVersionPresentWindows
    dockerfile_lines:
      - ADD https://download.newrelic.com/infrastructure_agent/binaries/windows/amd64/newrelic-infra-amd64.1.77.1.zip C:/nra.zip
      - RUN Expand-Archive -Path 'C:\nra.zip' -DestinationPath 'C:\' -Force; Write-Host '=== EXTRACTED CONTENTS ==='; Get-ChildItem 'C:\Program Files\New Relic\newrelic-infra\' | Select-Object FullName
      - COPY ["tasks/infra/config/fixtures/minimal_infra_config/newrelic-infra.yml", "C:/Program Files/New Relic/newrelic-infra/newrelic-infra.yml"]
    docker_cmd: ./nrdiag_x64.exe -y -filter all
    log_entry_expected:
     - Info.*Infra/Agent/Version.*
    log_entry_not_expected:
