name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}
      - name: debug github event
        run: |
          echo "tags:"
          echo ${GITHUB_REF#refs/tags/}
          echo "build:" 
          echo ${GITHUB_REF#refs/tags/build/}
          echo "labels:" 
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "event PR:"
          echo "${{ toJson(github.event.pull_request) }}"


