name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub ref
        run: echo "$GITHUB_REF"
      - name: debug github event
        run: |
          echo "tags:"
          echo ${GITHUB_REF#refs/tags/}
          echo "build:" 
          echo ${GITHUB_REF#refs/tags/build/}
          echo "labels:" 
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "event PR:"
          echo "${{ toJson(github.event.pull_request) }}"


